What is NumPy?
---------------
    1. NumPy stands for Numerical Python.
    2. NumPy is a Python library used for working with arrays.
    3. It also has functions for working in domain of linear algebra, fourier transform, and matrices.

Why Use NumPy?
---------------
    1. In Python we have lists that serve the purpose of arrays, but they are slow to process.
    2. NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
    3. The array object in NumPy is called ndarray

Why is NumPy Faster Than Lists?
--------------------------------
    1. NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.


Creating NumPy Arrays :
-----------------------
From a Python List :
--------------------
    1. We can create an array by directly converting a list or list of lists:

In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]
print(my_list,type(my_list))

[1, 2, 3] <class 'list'>


In [3]:
a = np.array(my_list)

print(a,type(a))

[1 2 3] <class 'numpy.ndarray'>


In [8]:
# One Dimention array

n1 = np.array([10,20,30,40,50])

print(n1,type(n1))

[10 20 30 40 50] <class 'numpy.ndarray'>


In [5]:
# Two Dimention array or Multi Dimention array

my_matrix1 = np.array([[1,2,3,4],[4,3,2,1]])

print(my_matrix1)

[[1 2 3 4]
 [4 3 2 1]]


In [9]:
# Three Dimention array or Multi Dimention array

my_matrix2 = np.array([[1,2,3,4],[4,3,2,1],[1,3,2,1]])

print(my_matrix2)

[[1 2 3 4]
 [4 3 2 1]
 [1 3 2 1]]


Arange :
--------
    1. Return evenly spaced values within a given interval.

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

zeros and ones :
----------------
    1. Generate arrays of zeros or ones

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones(3)

array([1., 1., 1.])

In [10]:
np.ones((3,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

Linspace :
----------
    1. Return evenly spaced numbers over a specified interval.

In [14]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [12]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [13]:
np.linspace(0, 10, 50, dtype=int,)

array([ 0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  3,  3,
        3,  3,  3,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  6,  6,  6,  6,
        6,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  9,  9,  9,  9, 10])

Eye :
-----

    1. Creates an identity matrix

In [16]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [17]:
np.eye(2,10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [3]:
np.eye(3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [7]:
np.eye(2,10, dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0]])

Random :
--------
    Numpy also has lots of ways to create random number arrays:

rand :
------
    Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

In [25]:
np.random.rand(2)

array([0.19352864, 0.83738102])

In [41]:
np.random.rand(3,2)

array([[0.22073894, 0.04101758],
       [0.83505864, 0.78859086],
       [0.99926656, 0.49199979]])

randn :
-------
    Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [36]:
np.random.randn()

0.10462972188642589

In [28]:
np.random.randn(2)

array([-0.24016306, -0.13054033])

In [39]:
np.random.randn(2, 4)

array([[ 1.28355111,  0.76060513, -0.58160699, -2.28990943],
       [ 1.78545377, -0.69013819, -0.99262149,  0.14448306]])

In [15]:
np.random.randn(2, 3)

array([[ 2.10143186,  1.05532344,  1.00018533],
       [-2.24019568, -0.51046573, -1.58296663]])

Randint :
---------

    Return random integers from low (inclusive) to high (exclusive).

In [16]:
np.random.randint(1,100)

23

In [19]:
a = np.random.randint(1,100,10)

a

array([65, 42, 96, 36, 93, 92, 48, 37, 25, 70], dtype=int32)

Array Attributes and Methods
----------------------------

Let's discuss some useful attributes and methods or an array:
-------------------------------------------------------------

In [21]:
arr = np.arange(25)

ranarr = np.random.randint(0,50,10)

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
ranarr

array([27, 31,  8, 24, 41,  3, 18, 42, 42, 40], dtype=int32)

01 Reshape :
------------
    Returns an array containing the same data with a new shape.

In [29]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:
ranarr2 = np.random.randint(0,50,9)

ranarr2

array([18, 43, 12, 23, 34, 30, 41, 17, 11], dtype=int32)

In [32]:
ranarr2.reshape(3,3)

array([[18, 43, 12],
       [23, 34, 30],
       [41, 17, 11]], dtype=int32)

02 max,min,argmax,argmin
------------------------
    These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [33]:
ranarr

array([27, 31,  8, 24, 41,  3, 18, 42, 42, 40], dtype=int32)

In [34]:
ranarr.max()

np.int32(42)