NumPy Indexing and Selection :
------------------------------

In [1]:
import numpy as np

In [17]:
#Creating sample array
arr = np.array([10,20,30,40,50,60,70,80,90,100])

In [18]:
#Show
arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

Bracket Indexing and Selection :
--------------------------------

        The simplest way to pick one or some elements of an array looks very similar to python lists.

In [19]:
#Get a value at an index
arr[8]

np.int64(90)

In [20]:
#Get values in a range
arr[1:5]

array([20, 30, 40, 50])

In [21]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,  60,  70,  80,  90, 100])

In [22]:
#Creating sample array
arr = np.arange(0,11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [25]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

Now note the changes also occur in our original array! :
--------------------------------------------------------

In [28]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Data is not copied, it's a view of the original array! This avoids memory problems! :
-------------------------------------------------------------------------------------

        In NumPy, when you slice or subset an array, it doesn’t create a new array but instead creates a "view" of the original data. This means that if you modify the view, it will also affect the original array, avoiding extra memory usage.

In [34]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100,   8,   9,  10])

In [40]:
arr[1:3]=300

#Show
arr

array([200, 300, 300, 100, 100, 100, 100, 100,   8,   9,  10])

In [41]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100,   8,   9,  10])

In [42]:
arr

array([200, 300, 300, 100, 100, 100, 100, 100,   8,   9,  10])

Broadcasting :
--------------

        The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations.

In [8]:
# Creating a NumPy array
arr = np.array([1, 2, 3, 4])
print(arr * 2)  # Output: [2 4 6 8]

[2 4 6 8]


In [12]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

# Broadcasting occurs here, aligning arr1 to match arr2's dimensions
result = arr1 + arr2
print(result)

[2 4 6]


In [13]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([[1], [2], [3]])

# Broadcasting occurs here, aligning arr1 to match arr2's dimensions
result = arr1 + arr2
print(result)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [14]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
print(np.sum(arr, axis=0))  # Sum along columns
print(np.sum(arr, axis=1))  # Sum along rows


[ 9 12]
[ 3  7 11]


In [15]:
# Compute the distance from origin for multiple 2D points
points = np.array([[1, 2], [3, 4], [5, 6]])
distance_from_origin = np.sqrt(np.sum(points**2, axis=1))
print(distance_from_origin)  # Output: [2.236 5.    7.810]


[2.23606798 5.         7.81024968]


Indexing a multi Dimention array (matrices) :
---------------------------------------------

        The general format is arr_2d[row][col] or arr_2d[row,col]. I recommend usually using the comma notation for clarity.

In [59]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [60]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [61]:
# Getting individual element value
arr_2d[1][0]

np.int64(20)

In [69]:
# slicing multi dimention array

#Shape (3,2) (rows, column)

arr_2d[:3,1:3]

array([[10, 15],
       [25, 30],
       [40, 45]])

In [68]:
#Shape (2,2) 
arr_2d[:2,1:3]

array([[10, 15],
       [25, 30]])

In [70]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

Fancy Indexing :
----------------

        Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array.

In [118]:
#Set up matrix
arr2d = np.zeros((10,10))

arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [119]:
#Length of array
arr_length = arr2d.shape[0]

arr_length

10

In [120]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i

print('-------------------------------------------')

arr2d

-------------------------------------------


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

Fancy indexing allows the following :
-------------------------------------

In [121]:
arr2d[[1,3,5,7,9]]

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [122]:
#Allows in any order

arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

Selection
---------
        Let's briefly go over how to use brackets for selection based off of comparison operators.

In [131]:
arr = np.array([10,20,30,40,50,60,70,80,90,100])
arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [133]:
arr > 40

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [134]:
bool_arr = arr > 40

bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [135]:
arr[bool_arr]

array([ 50,  60,  70,  80,  90, 100])

In [138]:
arr[arr > 30]

array([ 40,  50,  60,  70,  80,  90, 100])

In [139]:
x = 20
arr[arr > x]

array([ 30,  40,  50,  60,  70,  80,  90, 100])