Python Numpy Read and Write Text Files
--------------------------------------

In [1]:
import numpy as np

In [16]:
x = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]], np.int32)

In [18]:
np.savetxt("test.txt", x)

In [19]:
y = np.loadtxt('test.txt')

print(y)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
